In [12]:
import pandas as pd
import numpy as np 
import matplotlib.pyplot as plt 
%matplotlib inline 
from sklearn.linear_model import LinearRegression

import warnings
warnings.filterwarnings('ignore',category =FutureWarning)
warnings.filterwarnings('ignore')

In [8]:
df = pd.read_csv(r'E:\AI\LibrariesForAI\SupervisedLearning\1_Simple_linear_regression\homeprices.csv')
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [9]:
x_df = df.drop("price",axis=1)
x_df

area
0  2600
1  3000
2  3200
3  3600
4  4000

In [10]:
y_df = df.drop("area",axis=1)
y_df

price
0  550000
1  565000
2  610000
3  680000
4  725000

In [13]:
# create linear reg object
lr = LinearRegression()
lr.fit(x_df, y_df)

LinearRegression()

In [14]:
lr.coef_

array([[135.78767123]])

In [18]:
lr.intercept_

array([180616.43835616])

Saving trained model using - Pickle file


In [17]:
# import this library


import pickle

In [44]:
#saving

with open('lr_model_housePrice_Pickle','wb') as file:
    pickle.dump(lr,file)

In [45]:
#loading

with open('lr_model_housePrice','rb') as file:
    mp = pickle.load(file)

In [46]:
mp.coef_

array([[135.78767123]])

In [47]:
mp.predict([[100]])

array([[194195.20547945]])

In [48]:
## examples of with open


# create a file named sample.json with some data
import json

In [49]:
sampleJson = {
    
    'name':'jerry',
    'age':24
}

sampleJson

{'name': 'jerry', 'age': 24}

In [50]:
jsonObject = json.dumps(sampleJson)
jsonObject

'{"name": "jerry", "age": 24}'

In [51]:
with open('sample.json','w') as file:
    file.write(jsonObject)

In [52]:
with open('sample.json','r') as file:
    sample_read = json.load(file)

sample_read

{'name': 'jerry', 'age': 24}

Saving trained model using - Joblib


In [43]:
import joblib

In [54]:
joblib.dump(lr,'lr_model_houseprice_Joblib')

['lr_model_houseprice_Joblib']

In [55]:
mj = joblib.load('lr_model_houseprice_Joblib')

In [56]:
mj.coef_

array([[135.78767123]])

In [57]:
mj = joblib.load('lr_model_houseprice_Pickle')

In [58]:
mj.coef_

array([[135.78767123]])