In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
import warnings
warnings.filterwarnings('ignore',category = FutureWarning)
warnings.filterwarnings('ignore')
from sklearn.linear_model import LinearRegression

In [10]:
df = pd.read_csv('homeprices.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [11]:
df.bedrooms.fillna(df.bedrooms.median(),inplace=True)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [14]:
x_df = df.drop('price',axis=1)
y_df = df.price

In [16]:
lr = LinearRegression()
lr.fit(x_df, y_df)

LinearRegression()

In [18]:
lr.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [19]:
lr.intercept_

221323.0018654043

In [20]:
lr.predict([[2600,3.0,20]])

array([518217.63297611])

In [24]:
# predictive function
# price = 112.06244194*area + 23388.88007794*bedrooms + -3231.71790863*age + 221323.0018654043

112.06244194*2600 + 23388.88007794*3 + -3231.71790863*20 + 221323.0018654043

518217.6329706243

In [27]:
lr.predict([[3000,3,40]])

array([498408.25158031])