In [64]:
# install python package - NumPy

In [65]:
## pip install numpy

In [2]:
import numpy as np

# np is an alias name

In [67]:
myList=[1,2,3]

In [68]:
print(myList)

[1, 2, 3]


In [69]:
myList

[1, 2, 3]

In [70]:
type(myList)

list

In [71]:
#dir(np)

In [72]:
#help(np)

In [73]:
#np.array(myList)
arr=np.array(myList)

In [74]:
print(type(arr))

<class 'numpy.ndarray'>


In [75]:
# nd array = n dimensional array

In [76]:
# shape of array
arr.shape

(3,)

In [77]:
arr.size

3

In [78]:
my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

In [79]:
arr = np.array([my_lst1,my_lst2,my_lst3])

In [80]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [81]:
arr.shape

(3, 5)

In [82]:
arr.size

15

In [83]:
l1=[1,3,5]
l2=[4,5,6]
l3=[8,6,4]

In [84]:
array1=np.array([l1,l2,l3])

In [85]:
print(array1)

[[1 3 5]
 [4 5 6]
 [8 6 4]]


In [86]:
# NumPy array indexing

myList=[1,2,3,4,5]
arr=np.array(myList)

In [87]:
print(arr[0])

1


In [88]:
print(arr[1])

2


In [89]:
print("the third element is",arr[2],"and the fourth element is",arr[3])

the third element is 3 and the fourth element is 4


In [90]:
# Access 2D array

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])

In [91]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [92]:
# to print first row first element
arr[0,0]

1

In [93]:
arr[0]

array([1, 2, 3, 4, 5])

In [94]:
# access 2nd row 5th column
arr[1,4]

6

In [95]:
# print the var
# get shape
# get size
# index: first row first element
# index: sec row third element

valArr = np.array([[1,2,3],[4,5,6]])

print('The given array is: \n',valArr)
print('\n shape is:',valArr.shape)
print('\n size is:',valArr.size)
print('\n first row first element:',valArr[0,0])
print('\n second row third element :',valArr[1,2])

The given array is: 
 [[1 2 3]
 [4 5 6]]

 shape is: (2, 3)

 size is: 6

 first row first element: 1

 second row third element : 6


In [96]:
# create  a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
newArr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5],
       [11, 12, 13, 14, 15],
       [20, 25, 30, 35, 40]])

In [97]:
valArr = np.array([[1,2,3],[4,5,6]])
print(valArr)

[[1 2 3]
 [4 5 6]]


In [98]:
# print first row,last element
valArr[0,-1]

3

In [99]:
valArr[0]

array([1, 2, 3])

In [100]:
# NumPy array slicing - 1D

myList = [1,2,3,4,5,6,7,8,9,10]

arr = np.array(myList)

In [101]:
# arr[start:end]
arr[0:5]

array([1, 2, 3, 4, 5])

In [102]:
arr[:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [103]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [104]:
arr[:5]

array([1, 2, 3, 4, 5])

In [105]:
arr[-3:-1]

array([8, 9])

In [106]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [107]:
# step

arr[0:5:2]

array([1, 3, 5])

In [108]:
arr[::2]

array([1, 3, 5, 7, 9])

In [109]:
# Slicing - 2 D Arrays

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr = np.array([my_lst1,my_lst2,my_lst3])
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [110]:
arr[:,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [111]:
arr[0:2,:]

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6]])

In [112]:
arr[:,:1]

array([[1],
       [2],
       [9]])

In [113]:
arr[:1,:]

array([[1, 2, 3, 4, 5]])

In [114]:
arr[1,2:4]

array([4, 5])

In [115]:
# Arange function

np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
np.arange(5,10)

array([5, 6, 7, 8, 9])

In [120]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [1]:
import numpy as np

In [11]:
arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int32


In [12]:
arr = np.array([1, 2, 3, 4, 5],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4' b'5']
|S1


In [19]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.int64)
print(arr)
print(arr.dtype)

[1 2 3 4 5]
int64


In [20]:
arr

array([1, 2, 3, 4, 5], dtype=int64)

In [21]:
arr = np.array([1, 2, 3, 4, 5],dtype=np.float64)
print(arr)
print(arr.dtype)

[1. 2. 3. 4. 5.]
float64


In [22]:
arr

array([1., 2., 3., 4., 5.])

In [25]:
# Array math

x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])


In [29]:
print(x)
print('   ')
print(y)

[[1 2]
 [3 4]]
   
[[5 6]
 [7 8]]


In [31]:
np.add(x,y)

array([[ 6,  8],
       [10, 12]])

In [34]:
x+y

array([[ 6,  8],
       [10, 12]])

In [32]:
np.multiply(x,y)

array([[ 5, 12],
       [21, 32]])

In [35]:
x*y

array([[ 5, 12],
       [21, 32]])

In [33]:
np.subtract(x,y)

array([[-4, -4],
       [-4, -4]])

In [37]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [38]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [39]:
np.square(x)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [ ]:
#  x = np.array([[1,2],[3,4]], dtype=np.float64)
#  y = np.array([[5,6],[7,8],[9,10]], dtype=np.float64)
# cant do multiplication since no of rows of x not same as no of col in y

In [40]:
np.sin(x)

array([[ 0.84147098,  0.90929743],
       [ 0.14112001, -0.7568025 ]])

In [41]:
np.log(x)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [43]:
 x = np.array([[1.9,2.5],[3.2,4]])

In [44]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [45]:
np.ceil(x)

array([[2., 3.],
       [4., 4.]])

In [46]:
np.round(x)

array([[2., 2.],
       [3., 4.]])

In [47]:
np.exp(x)

array([[ 6.68589444, 12.18249396],
       [24.5325302 , 54.59815003]])

In [62]:
x = np.array([[1,2],[3,4]])
y = np.array([[1,1],[1,1]])
z = np.array([[0,0],[0,0]])

In [63]:
x*y*z

array([[0, 0],
       [0, 0]])

In [64]:
np.multiply(x,y,z)

array([[1, 2],
       [3, 4]])

In [68]:
x = np.array([[1,2],[3,4]])
np.sum(x)

10

In [3]:
# NumPy Array Copy vs View



# NumPy Array view

arr = np.array([1, 2, 3, 4, 5])
x = arr

In [4]:
print(arr)

[1 2 3 4 5]


In [5]:
print(x)

[1 2 3 4 5]


In [6]:
arr[0] = 100
print(arr)
print(x)

[100   2   3   4   5]
[100   2   3   4   5]


In [7]:
x[1]=200
print(arr)
print(x)

[100 200   3   4   5]
[100 200   3   4   5]


In [12]:
# NumPy Array copy

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()

In [13]:
arr[0] = 100
print(arr)

[100   2   3   4   5]


In [14]:
print(x)

[1 2 3 4 5]


In [15]:
x[1]=200
print(x)

[  1 200   3   4   5]


In [17]:
print(arr)

[100   2   3   4   5]


In [ ]:
# NumPy array re shaping

In [22]:
arr=np.arange(1,13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [19]:
arr.shape

(12,)

In [23]:
arr.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
new_arr = arr.reshape(3,4)   # 1d------2d
new_arr

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
# Flattening of array

new_arr.reshape(-1)         # 2d-------1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
arr=np.arange(1,13).reshape(4,3)

In [31]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [36]:
# iterating Arrays

for x in arr:
    print(x)

[1 2 3]
[4 5 6]
[7 8 9]
[10 11 12]


In [39]:
# Joining arrays

# Joining NumPy Arrays # 1D
arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

In [40]:
np.concatenate((arr1,arr2))

array([1, 2, 3, 4, 5, 6])