## Numpy Tutorials

NumPy is a general-purpose array-processing package. It provides a high-performance multidimensional array object, and tools for working with these arrays. It is the fundamental package for scientific computing with Python.

### What is an array

An array is a data structure that stores values of same data type. 

In Python, this is the main difference between arrays and lists. While python lists can contain values corresponding to different data types, arrays in python can only contain values corresponding to same data type

### Install Libraries

In [2]:
# pip install numpy

In [3]:
import numpy 

### Check the in-built Function in Numpy

In [21]:
# dir(np)

### Help Function

In [24]:
# help(np)

In [9]:
myList=[1, 2, 3, 4, 5]
arr = numpy.array(myList)
print(arr)

[1 2 3 4 5]


### NumPy as np

NumPy is usually imported under the np alias.

alias: In Python alias are an alternate name for referring to the same thing.

Create an alias with the as keyword while importing:

In [1]:
import numpy as np

#### Create a NumPy ndarray Object

NumPy is used to work with arrays. The array object in NumPy is called ndarray.

We can create a NumPy ndarray object by using the array() function.

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print(arr)

print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# show the shape of the array
arr.shape  

(5,)

In [4]:
#number of elements in the array
arr.size 

5

#### Notes:
    
type(): This built-in Python function tells us the type of the object passed to it. Like in above code it shows that arr is numpy.ndarray type.

To create an ndarray, we can pass a list, tuple or any array-like object into the array() method, and it will be converted into an ndarray:

#### Multinested array

In [15]:

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

In [14]:
arr

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [17]:
type(arr)

numpy.ndarray

In [18]:
## check the shape of the array
arr.shape

(3, 5)

#### NumPy Array Indexing

Access Array Elements

Array indexing is the same as accessing an array element.

You can access an array element by referring to its index number.

The indexes in NumPy arrays start with 0, meaning that the first element has index 0, and the second has index 1 etc.

In [30]:
# Get the first element from the following array:

mylist=[1, 2, 3, 4]

arr = np.array(mylist)

print(arr[0])

1


In [33]:
# Get the second element from the following array.


mylist=[1, 2, 3, 4]

arr = np.array(mylist)

print(arr[1])

2


In [37]:
# Get third and fourth elements from the following array and add them.

mylist=[1, 2, 3, 4]

arr = np.array(mylist)

print("The third elements is: ", arr[2]," and fourth elements is: ", arr[3])

The third elements is:  3  and fourth elements is:  4


#### Access 2-D Arrays

To access elements from 2-D arrays we can use comma separated integers representing the dimension and the index of the element.

Think of 2-D arrays like a table with rows and columns, where the row represents the dimension and the index represents the column.

In [39]:
# Access the element on the first row, second column:

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

print('2nd element on 1st row: ', arr[0, 1])

2nd element on 1st row:  2


In [40]:
# Access the element on the 2nd row, 5th column:


print('5th element on 2nd row: ', arr[1, 4])


5th element on 2nd row:  6


In [14]:
# More Exmaple

valArr = np.array([[1,2,3],[4,5,6]])    # Create a 2D array
print(valArr)
print(valArr.shape)  # Prints "(2, 3)"\
print(valArr.size)
#indexing using both row and column
print(valArr[0,0])
print(valArr[1,1])



[[1 2 3]
 [4 5 6]]
(2, 3)
6
1
5


In [16]:
# create  a 5*5 array
newArr= np.array([[1,2,3,4,5],[6,7,8,9,10],[1,2,3,4,5],[11,12,13,14,15],[20,25,30,35,40]])
print(newArr)
print(newArr.shape)  # Prints "(2, 3)"\
print(newArr.size)
#indexing using both row and column
print(newArr[3,2])
print(newArr[4,1])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]
 [11 12 13 14 15]
 [20 25 30 35 40]]
(5, 5)
25
13
25


#### Negative Indexing
Use negative indexing to access an array from the end.

In [45]:
# Print the last element from the 2nd dim:
print('Last element from 2nd dim: ', arr[1, -1])

Last element from 2nd dim:  6


#### NumPy Array Slicing

Slicing arrays

Slicing in python means taking elements from one given index to another given index.

We pass slice instead of index like this: [start:end].

We can also define the step, like this: [start:end:step].

If we don't pass start its considered 0

If we don't pass end its considered length of array in that dimension

If we don't pass step its considered 1

In [114]:
# Slice elements from index 1 to index 5 from the following array:
mylist=[1, 2, 3, 4, 5, 6, 7, 8]

arr = np.array(mylist)

print(arr[1:5])

[2 3 4 5]


Note: The result includes the start index, but excludes the end index.

In [48]:
# Slice elements from index 4 to the end of the array:

print(arr[4:])

[5 6 7 8]


In [50]:
# Slice elements from the beginning to index 4 (not included):

print(arr[:4])

[1 2 3 4]


#### Negative Slicing

In [121]:
# Slice from the index 3 from the end to index 1 from the end:
print(arr[-3:-1])

print(arr[:-1])

[6 7]
[1 2 3 4 5 6 7]


#### STEP

In [122]:
# Use the step value to determine the step of the slicing:

# Return every other element from index 1 to index 5:
mylist=[1, 2, 3, 4, 5, 6, 7, 8]

arr = np.array(mylist)

print(arr[1:5:2])

[2 4]


In [55]:
# Return every other element from the entire array:

print(arr[::2])

[1 3 5 7]


#### Slicing 2-D Arrays

In [123]:
# From the second element, slice elements from index 1 to index 4 (not included):

my_lst1=[1,2,3,4,5]
my_lst2=[2,3,4,5,6]
my_lst3=[9,7,6,8,9]

arr=np.array([my_lst1,my_lst2,my_lst3])

print(arr[1, 1:4])

[3 4 5]


Note: Remember that second element has index 1.

In [133]:
# From both elements, return index 2:

print(arr[0:2,2])
print(arr[0:3,1])

[3 4]
[2 3 7]


In [64]:
# From both elements, slice index 1 to index 4 (not included), this will return a 2-D array:

print(arr[0:2, 1:4])

[[2 3 4]
 [3 4 5]]


In [70]:
# accessing all the data
print(arr[:,:])

[[1 2 3 4 5]
 [2 3 4 5 6]
 [9 7 6 8 9]]


In [76]:
# Accessing the row 1 and column 2
print(arr[1:,:2])

[[2 3]
 [9 7]]


In [78]:
# Accessing the entire row  and column from 3 index
print(arr[:,3:])

[[4 5]
 [5 6]
 [8 9]]


In [20]:
# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
silArr = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [21]:
print(silArr)
# Use slicing to pull out the subarray consisting of the first 2 rows
# and columns 1 and 2; b is the following array of shape (2, 2):
# [[2 3]
#  [6 7]]
silArr[:2, 1:3]

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


array([[2, 3],
       [6, 7]])

In [23]:
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(silArr[0, 1])   # Prints "2"

2


#### Arange function

In [134]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [136]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [137]:
np.arange(10,0,-1)

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

### Linspace

In [94]:
np.linspace(0, 100, num=5)  #5 eqidistant elements from 1 to 100 

array([  0.,  25.,  50.,  75., 100.])

In [138]:
np.linspace(100,0,5)

array([100.,  75.,  50.,  25.,   0.])

#### NumPy Data Types

Data Types in Python

By default Python have these data types:

- strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"

- integer - used to represent integer numbers. e.g. -1, -2, -3

- float - used to represent real numbers. e.g. 1.2, 42.42

- boolean - used to represent True or False.

- complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

Data Types in NumPy

NumPy has some extra data types, and refer to data types with one character, like i for integers, u for unsigned integers etc.

Below is a list of all data types in NumPy and the characters used to represent them.

- i - integer

- b - boolean

- u - unsigned integer

- f - float

- c - complex float

- m - timedelta
 
- M - datetime
 
- O - object
 
- S - string
 
- U - unicode string
 
- V - fixed chunk of memory for other type ( void )

In [139]:
# Get the data type of an array object:

arr = np.array([1, 2, 3, 4]) # Let numpy choose the datatype

print(arr.dtype)
 

int32


In [140]:
x = np.array([10, 20])   # Let numpy choose the datatype
print(x.dtype)         # Prints "int32"

int32


In [141]:
arr = np.array([1.0, 2.0])   # Let numpy choose the datatype
print(arr.dtype)             # Prints "float64"

float64


In [84]:
#Get the data type of an array containing strings:

arr = np.array(['apple', 'banana', 'cherry'])

print(arr.dtype)

<U6


#### Creating Arrays With a Defined Data Type
We use the array() function to create arrays, this function can take an optional argument: dtype that allows us to define the expected data type of the array elements:

In [142]:
# Create an array with data type string:
arr = np.array([1, 2, 3, 4], dtype='S')

print(arr)
print(arr.dtype)

# For i, u, f, S and U we can define size as well.

[b'1' b'2' b'3' b'4']
|S1


In [99]:
# Create an array with data type 4 bytes integer:

arr = np.array([1, 2, 3, 4], dtype='i')

print(arr)
print(arr.dtype)

[1 2 3 4]
int32


In [107]:
arr = np.array([1, 2], dtype=np.int64)   # Force a particular datatype
print(arr.dtype)                          # Prints "int64"

int64


In [108]:
arr = np.array([1, 2], dtype=np.float32)   # Force a particular datatype
print(arr.dtype)     

float32


In [114]:
arr = np.array([1.9999, 2.5],dtype = np.int32)   # Let numpy choose the datatype
print(arr.dtype)             # Prints "float64"
print(arr)

int32
[1 2]


#### Array math

In [46]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)

In [47]:
print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [49]:
#Addition

x+y #element level matrix addition

array([[ 6.,  8.],
       [10., 12.]])

In [51]:
np.add(x,y) #element level matrix addition

array([[ 6.,  8.],
       [10., 12.]])

In [50]:
#subtraction

x-y #element level matrix subtraction

array([[-4., -4.],
       [-4., -4.]])

In [52]:
np.subtract(x,y)

array([[-4., -4.],
       [-4., -4.]])

In [53]:
y-x

array([[4., 4.],
       [4., 4.]])

In [54]:
np.subtract(y,x)

array([[4., 4.],
       [4., 4.]])

In [55]:
# multiplication

x*y  ##element level matrix multiplication

array([[ 5., 12.],
       [21., 32.]])

In [56]:
np.multiply(x, y)

array([[ 5., 12.],
       [21., 32.]])

In [57]:
# division

x/y ##element level matrix division

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [58]:
np.divide(x,y)

array([[0.2       , 0.33333333],
       [0.42857143, 0.5       ]])

In [59]:
y/x

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [60]:
np.divide(y,x)

array([[5.        , 3.        ],
       [2.33333333, 2.        ]])

In [61]:
np.sqrt(x)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [62]:
np.sqrt(y)

array([[2.23606798, 2.44948974],
       [2.64575131, 2.82842712]])

In [63]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8],[9,10]], dtype=np.float64)

In [64]:
np.add(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [65]:
np.subtract(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [66]:
np.multiply(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [67]:
np.divide(x,y)

ValueError: operands could not be broadcast together with shapes (2,2) (3,2) 

In [68]:
np.exp(x) #element level exponential 

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [69]:
np.log(x) #element level log

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436]])

In [70]:
np.cos(x)

array([[ 0.54030231, -0.41614684],
       [-0.9899925 , -0.65364362]])

In [71]:
np.tan(x)

array([[ 1.55740772, -2.18503986],
       [-0.14254654,  1.15782128]])

#### Floor, Ceil, Round

In [72]:
x = np.array([[1.5,2.5],[3.1,4.9]], dtype=np.float64)

In [73]:
x

array([[1.5, 2.5],
       [3.1, 4.9]])

In [74]:
np.floor(x)

array([[1., 2.],
       [3., 4.]])

In [75]:
np.ceil(x)

array([[2., 3.],
       [4., 5.]])

In [76]:
np.round(x)

array([[2., 2.],
       [3., 5.]])

In [80]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
z = np.array([[9,10],[11,12]], dtype=np.float64)

In [81]:
x

array([[1., 2.],
       [3., 4.]])

In [82]:
y

array([[5., 6.],
       [7., 8.]])

In [83]:
z

array([[ 9., 10.],
       [11., 12.]])

In [84]:
# multiply
x*y*z

array([[ 45., 120.],
       [231., 384.]])

In [85]:
np.add(x,y,z) #only first 2 paramters are considered

array([[ 6.,  8.],
       [10., 12.]])

In [86]:
np.multiply(x,y,z) #only first 2 paramters are considered

array([[ 5., 12.],
       [21., 32.]])

In [10]:
import numpy as np
x = np.array([[1,2],[3,4],[5,6]])
y = np.array([[5,6],[7,8]])

v = np.array([9,10])
w = np.array([11, 12])

In [88]:
v

array([ 9, 10])

In [89]:
w

array([11, 12])

In [90]:
v.dot(w)

219

In [91]:
np.dot(v,w)

219

In [92]:
x.dot(v)

array([29, 67])

In [9]:
x.dot(v)

array([ 29,  67, 105])

In General:

To multiply an m×n matrix by an n×p matrix, the ns must be the same,and the result is an m×p matrix.



In [14]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [17]:
print(x)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [15]:
np.sum(x)

45

In [16]:
np.sum(x,axis=0) # row wise add

array([12, 15, 18])

In [18]:
np.sum(x,axis=1)  # column wise add

array([ 6, 15, 24])

In [19]:
x.T # Transpose

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
x.T.T

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

#### NumPy Array Copy vs View

The Difference Between Copy and View

The main difference between a copy and a view of an array is that the copy is a new array, and the view is just a view of the original array.

The copy owns the data and any changes made to the copy will not affect original array, and any changes made to the original array will not affect the copy.

The view does not own the data and any changes made to the view will affect the original array, and any changes made to the original array will affect the view.

#### COPY:

In [120]:
# Make a copy, change the original array, and display both arrays:

arr = np.array([1, 2, 3, 4, 5])
x = arr.copy()
arr[0] = 42

print(arr)
print(x)

###  The copy SHOULD NOT be affected by the changes made to the original array.

[42  2  3  4  5]
[1 2 3 4 5]


#### VIEW:

In [124]:
# Make a view, change the original array, and display both arrays:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
arr[0] = 42

print(arr)
print(x)

### The view SHOULD be affected by the changes made to the original array.

[42  2  3  4  5]
[42  2  3  4  5]


In [125]:
# Make Changes in the VIEW:
arr = np.array([1, 2, 3, 4, 5])
x = arr.view()
x[0] = 31

print(arr)
print(x)

[31  2  3  4  5]
[31  2  3  4  5]


#### Check if Array Owns its Data

As mentioned above, copies owns the data, and views does not own the data, but how can we check this?

Every NumPy array has the attribute base that returns None if the array owns the data.

Otherwise, the base  attribute refers to the original object.

In [127]:
# Print the value of the base attribute to check if an array owns it's data or not:

x = arr.copy()
y = arr.view()

print(x.base)
print(y.base)

# The copy returns None.
# The view returns the original array.

None
[31  2  3  4  5]


#### NumPy Array Shape

Shape of an Array

The shape of an array is the number of elements in each dimension.


Get the Shape of an Array

NumPy arrays have an attribute called shape that returns a tuple with each index having the number of corresponding elements.

In [130]:
# Print the shape of a 2-D array:
arr = np.array([[1, 2, 3, 4], 
                [5, 6, 7, 8]])

print(arr.shape)

# The example above returns (2, 4), which means that the array has 2 dimensions, 
# where the first dimension has 2 elements and the second has 4.

(2, 4)


In [131]:
# Create an array with 5 dimensions using ndmin using a vector with values 1,2,3,4 and 
# verify that last dimension has value 4:

arr = np.array([1, 2, 3, 4], ndmin=5)

print(arr)
print('shape of array :', arr.shape)

[[[[[1 2 3 4]]]]]
shape of array : (1, 1, 1, 1, 4)


#### NumPy Array Reshaping

Reshaping means changing the shape of an array.

The shape of an array is the number of elements in each dimension.

By reshaping we can add or remove dimensions or change number of elements in each dimension.

####  Reshape From 1-D to 2-D

Convert the following 1-D array with 12 elements into a 2-D array.

The outermost dimension will have 4 arrays, each with 3 elements:

In [133]:

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(4, 3)

print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


#### Reshape From 1-D to 3-D

Convert the following 1-D array with 12 elements into a 3-D array.

The outermost dimension will have 2 arrays that contains 3 arrays, each with 2 elements:

In [105]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])

newarr = arr.reshape(2, 3, 2)

print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [106]:
newarr.reshape((5,5))  #size mismatch

ValueError: cannot reshape array of size 12 into shape (5,5)

In [107]:
newarr.reshape((3,3))  #size mismatch

ValueError: cannot reshape array of size 12 into shape (3,3)

#### Flattening the arrays

Flattening array means converting a multidimensional array into a 1D array.

We can use reshape(-1) to do this.

In [108]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

newarr = arr.reshape(-1)

print(newarr)

[1 2 3 4 5 6]


In [113]:
np.ravel(arr)

array([1, 2, 3, 4, 5, 6])

#### Iterating Arrays

Iterating means going through elements one by one.

As we deal with multi-dimensional arrays in numpy, we can do this using basic for loop of python.

If we iterate on a 1-D array it will go through each element one by one.

In [7]:
import numpy as np

arr = np.array([1, 2, 3])

for x in arr:
    print(x)

1
2
3


#### Iterating 2-D Arrays

In a 2-D array it will go through all the rows.

In [8]:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    print(x)

[1 2 3]
[4 5 6]


If we iterate on a n-D array it will go through n-1th dimension one by one.


In [10]:
# Iterate on each scalar element of the 2-D array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

for x in arr:
    for y in x:
        print(y)

1
2
3
4
5
6


#### Joining NumPy Arrays

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

Note : “axis 0” represents rows and “axis 1” represents columns

In [24]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


In [28]:
#Join two 2-D arrays along rows (axis=1):

arr1 = np.array([[1, 2], [3, 4]])

arr2 = np.array([[5, 6], [7, 8]])

arr = np.concatenate((arr1, arr2), axis=1)

print(arr)

[[1 2 5 6]
 [3 4 7 8]]


#### NumPy Splitting Array

Splitting NumPy Arrays

Splitting is reverse operation of Joining.

Joining merges multiple arrays into one and Splitting breaks one array into multiple.

We use array_split() for splitting arrays, we pass it the array we want to split and the number of splits.

In [30]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr)

#Note: The return value is an array containing three arrays.

[array([1, 2]), array([3, 4]), array([5, 6])]


In [31]:
#If the array has less elements than required, it will adjust from the end accordingly.

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)

print(newarr)

[array([1, 2]), array([3, 4]), array([5]), array([6])]


The return value of the array_split() method is an array containing each of the split as an array.

If you split an array into 3 arrays, you can access them from the result just like any array element:

In [32]:
arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


In [33]:
# Split the 2-D array into three 2-D arrays.

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


In [34]:
# Split the 2-D array into three 2-D arrays.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


In [35]:
#Split the 2-D array into three 2-D arrays along rows.
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [ ]:
NumPy Searching Arrays